#-------------------------------
# General Site Settings

title: TEAM CONNECTION
logo: 
author: themefisher
description: this is meta description
email: email@email.com
leader: s0unn#9437
# address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2022 TEAM CONNECTION

menu:
- {name: 소개, link: '/about'}
- {name: 업데이트, link: '/blog'}
# - {name: Po, link: '/portfolio'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: 사람과 <br> 사람을 <br> 연결합니다.

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  사람은 항상 사람과 상호작용합니다. 그 방식은 바꿀 수 없었죠. 그러나 저희는 그 방식을 바꾸어보려 합니다. 어떤가요? 함께 바꾸어 보실건가요?

blurb-btn-link: '/about'
blurb-btn-name: 더 알아보기


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Web Design, color: '#fdb157', value: '90%'}
# - {name: Logo Design, color: '#9473e6', value: '60%'}
# - {name: After Effects, color: '#bdecf6', value: '80%'}
# - {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: 이 친구는 많은 분들이 좋아하십니다.
experience:
- {name: 약 2천 개, icon: 'icon-1.png', date: '참가 중인 서버 수', organization: '2022년 4월'}
- {name: 약 12만 명, icon: 'icon-2.png', date: '이용자 수', organization: '2022년 4월'}
# - {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: '2022년 4월'}


#-------------------------------
# Education Section

# education-title: Education
# education:
# - {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
# - {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: 이 친구는 많은 역할을 하기도 하죠.
services:
- {
    name: 다양한 명령어,
    icon: ti-comment-alt,
    description: '서버 관리에 필요한 관리 명령어 뿐만 아니라 다양한 미니게임까지!',
    active: # Add true to select section
  }
- {
    name: 재밌는 미니게임,
    icon: ti-game,
    description: '지루했던 서버 생활에 한 줄기 빛을, 다양한 미니게임!',
    active: true # Add true to select section
  }
- {
    name: 다양한 커스텀 기능,
    icon: ti-wand,
    description: '마치 마법과 같습니다. 다양한 커스텀 기능!',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
# portfolio-home-items:
#  - image : "assets/images/portfolio/item-1.png"
#    url: "#"
    
#  - image : "assets/images/portfolio/item-2.png"
#    url: "#"
    
#  - image : "assets/images/portfolio/item-3.png"
 #   url: "#"
    
#  - image : "assets/images/portfolio/item-4.png"
#    url: "#"
#    
#  - image : "assets/images/portfolio/item-5.png"
 #   url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

# testimonial-items:
#  - name: "Jesica Gomez"
#    image: "assets/images/testimonial/client-1.png"
 #   designation : "CEO, Funder"
 #   content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

# client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: 도움이 필요하신가요?
contact-email: email@email.com
